### ISSUE TITLE
AWSPinpoint with Amplify v2

### ISSUE THREAD

**Issue by losetchi** [aws-amplify/amplify-ios#2548]
### Describe the bug

Hello. I am trying to migrate to Amplify v2. We are using Auth and Analytics plugins, for which migration to v2 went fine, but we have issues with using AWSPinpoint for notifications. On v1 everything worked fine, but since migrating to v2, we are unable to compile the code, getting **Cannot find type 'AWSPinpoint' in scope**. We also tried installing AWSPinpoint via CocoaPods but results are the same. We have same implementation as described here https://docs.amplify.aws/sdk/push-notifications/getting-started/q/platform/ios/#connect-to-your-backend
We did clean all the caches.

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Update Amplify to v2.
2. Try to run the project with AWSPinpoint.
```

### Expected behavior

We should be able to build AWSPinpoint for remote notifications.

### Amplify Framework Version

v2.0.2

### Amplify Categories

Analytics

### Dependency manager

Swift PM

### Swift version

5

### CLI version

10.4.0

### Xcode version

14.0

### Is this a regression?

Yes

### Device

iPhone 14 simulator

### iOS Version

iOS 16

**Comment by ruisebas** [comment]
Hi @losetchi, thanks for reaching out.

**AWS Pinpoint Push Notifications** support is part of **[aws-sdk-ios](https://github.com/aws-amplify/aws-sdk-ios)**'s `AWSPinpoint`, which in Amplify **v1.x** is provided via _Analytics_' escape hatch.

As Amplify **v2.x** has moved away from **aws-sdk-ios**, Pinpoint Push Notifications support is not yet available.
However we are currently looking into it.
