### ISSUE TITLE
Cannot find 'DispatchQueue' in scope 1.15.0 Library

### ISSUE THREAD

**Issue by rbanker** [aws-amplify/amplify-ios#1466]
### Describe the bug

In the latest build of Amplify (1.15.0), we are no longer able to compile our application using the iOS 14.5 SDK (Xcode 12.5.1).  In a new file added to the AWSDataStorePlugin in this release (DataStoreObserveQueryOperation.swift), we recieve the error "Cannot find 'DispatchQueue' in scope'.

### Steps To Reproduce

1. Add Amplify 1.15.0 to project in Swift Package Manager
2. Build project
3. Error will appear during build

```shell
/Users/xxxxxxxx/Library/Developer/Xcode/DerivedData/SCC-dcfbvhynqaojhnegqsncqzxfzlml/SourcePackages/checkouts/amplify-ios/AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Subscribe/DataStoreObserveQueryOperation.swift:40:31: Cannot find 'DispatchQueue' in scope
```

### Expected behavior

Project will compile successfully

### Amplify Framework Version

1.15.0

### Amplify Categories

DataStore

### Dependency manager

Swift PM

### Swift version

5.0

### CLI version

6.3.1

### Xcode version

12.5.1

### Relevant log output

```shell
/Users/***/Library/Developer/Xcode/DerivedData/SCC-dcfbvhynqaojhnegqsncqzxfzlml/SourcePackages/checkouts/amplify-ios/AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Subscribe/DataStoreObserveQueryOperation.swift:40:31: error: cannot find 'DispatchQueue' in scope
    private let serialQueue = DispatchQueue(label: "com.amazonaws.ObserveQuerySubscription.serialQueue",
                              ^~~~~~~~~~~~~
/Users/***/Library/Developer/Xcode/DerivedData/SCC-dcfbvhynqaojhnegqsncqzxfzlml/SourcePackages/checkouts/amplify-ios/AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Subscribe/DataStoreObserveQueryOperation.swift:41:53: error: cannot find 'DispatchQueue' in scope
                                            target: DispatchQueue.global())
                                                    ^~~~~~~~~~~~~
/Users/***/Library/Developer/Xcode/DerivedData/SCC-dcfbvhynqaojhnegqsncqzxfzlml/SourcePackages/checkouts/amplify-ios/AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Subscribe/DataStoreObserveQueryOperation.swift:115:31: error: cannot find 'DispatchQueue' in scope
    private let serialQueue = DispatchQueue(label: "com.amazonaws.AWSDataStoreObseverQueryOperation.serialQueue",
                              ^~~~~~~~~~~~~
/Users/***/Library/Developer/Xcode/DerivedData/SCC-dcfbvhynqaojhnegqsncqzxfzlml/SourcePackages/checkouts/amplify-ios/AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Subscribe/DataStoreObserveQueryOperation.swift:116:53: error: cannot find 'DispatchQueue' in scope
                                            target: DispatchQueue.global())
                                                    ^~~~~~~~~~~~~
/Users/****/Library/Developer/Xcode/DerivedData/SCC-dcfbvhynqaojhnegqsncqzxfzlml/SourcePackages/checkouts/amplify-ios/AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Subscribe/DataStoreObserveQueryOperation.swift:117:59: error: cannot find type 'DispatchQueue' in scope
    private let itemsChangedPeriodicPublishTimeInSeconds: DispatchQueue.SchedulerTimeType.Stride = 2
                                                          ^~~~~~~~~~~~~
```

### Is this a regression? (i.e. was this working before a version upgrade)

Yes.  Worked in Amplify 1.14.0

### Device

Simulator

### iOS Version

14

### Specific to simulators

No

**Comment by willi2i** [comment]
+1 Thought it was just me... installed xcode 13 beta just incase.... still got the issue...

**Comment by ameter** [comment]
This has been fixed in Amplify iOS v1.15.1

**Comment by azhong-git** [comment]
thank you for the quick fix. v1.15.1 worked for me
